highlighter: rouge
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE.md
- Rakefile
- Gemfile
- Gemfile.lock
